CREATE TABLE TEMP_SENSOR(
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL,
  CLASSIFICATION CHAR(32) NULL,
  CREATE_DATE timestamp NOT NULL,
  TEMP_VALUE VARCHAR(16) NOT NULL
);

CREATE TABLE PRES_SENSOR(
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL,
  CLASSIFICATION CHAR(32) NULL,
  CREATE_DATE timestamp NOT NULL,
  PRES_VALUE VARCHAR(16) NOT NULL
);
